#!/usr/bin/env python3
# patch-fnptr-agnos.py — STOPGAP patcher for the agnos target (agnoshi 1.4.x).
#
# WHY
#   cyrius/lib/fnptr.cyr's fncall0..fncall8 guard their inline-asm indirect-call
#   bodies on #ifdef CYRIUS_TARGET_LINUX / _MACOS / _WIN — there is NO
#   CYRIUS_TARGET_AGNOS branch. The agnos build predefines CYRIUS_TARGET_AGNOS
#   but deliberately NOT CYRIUS_TARGET_LINUX (cyrius/src/main.cyr:866-871), so on
#   agnos every fncallN compiles to `var result = 0; return result;` and returns
#   0. That silently breaks the Allocator vtable (alloc_via/realloc_via/free_via/
#   reset_via dispatch through fncall1/2/4) -> vec_new/str_new/hashmap via
#   default_alloc(). agnsh's first vtable-allocator consumer is
#   CommandHistory_new -> vec_new(), which returns null; the shell then faults
#   dereferencing it: banner prints, prompt never does.
#
# WHAT
#   The vendored lib/fnptr.cyr is gitignored and regenerated by `cyrius update`,
#   so this fix can't live in committed source. This script re-applies it: for
#   each fncallN it CLONES that function's own validated CYRIUS_TARGET_LINUX +
#   CYRIUS_ARCH_X86 asm block under a CYRIUS_TARGET_AGNOS guard, inserted right
#   after `var result = 0;`. Cloning the in-place block (rather than a separate
#   src override) is REQUIRED: the asm uses hardcoded [rbp-N] offsets that are
#   coupled to cycc's per-definition frame layout; a copied-out standalone
#   definition gets a different layout and crashes. agnos x86_64 == Linux SysV,
#   so the same bytes are correct here.
#
# WHEN
#   Run after every `cyrius update`/`cyrius deps` in this repo, BEFORE
#   `cyrius build --agnos`. Idempotent (no-op if already patched).
#
# REMOVE WHEN
#   cyrius/lib/fnptr.cyr ships a CYRIUS_TARGET_AGNOS branch on fncall0..8.
#   Tracking issue:
#   cyrius/docs/development/issues/2026-06-08-fnptr-fncall-missing-agnos-branch.md
#
# Usage:  python3 scripts/patch-fnptr-agnos.py [path/to/lib/fnptr.cyr]
import re, sys, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, "lib", "fnptr.cyr")

if not os.path.isfile(path):
    sys.stderr.write(f"patch-fnptr-agnos: {path} not found "
                     "(run `cyrius update`/`cyrius deps` in agnoshi first)\n")
    sys.exit(1)

src = open(path).read()

if "CYRIUS_TARGET_AGNOS" in src:
    print(f"patch-fnptr-agnos: {path} already patched (CYRIUS_TARGET_AGNOS present) — no-op")
    sys.exit(0)

# For each fncallN body: capture `var result = 0;` then its CYRIUS_TARGET_LINUX /
# CYRIUS_ARCH_X86 asm { ... } block, and insert an AGNOS clone of that asm block
# (same bytes) right after the `var result = 0;` line.
pat = re.compile(
    r"(    var result = 0;\n)"
    r"(    #ifdef CYRIUS_TARGET_LINUX\n    #ifdef CYRIUS_ARCH_X86\n)"
    r"(    asm \{\n.*?\n    \}\n)",
    re.DOTALL,
)

def repl(m):
    result_line, linux_guard, asm_block = m.group(1), m.group(2), m.group(3)
    agnos = ("    #ifdef CYRIUS_TARGET_AGNOS\n"
             "    #ifdef CYRIUS_ARCH_X86\n"
             + asm_block +
             "    #endif\n"
             "    #endif\n")
    return result_line + agnos + linux_guard + asm_block

new, n = pat.subn(repl, src)
if n == 0:
    sys.stderr.write("patch-fnptr-agnos: no fncallN Linux/x86 asm blocks matched — "
                     "fnptr.cyr layout changed; inspect manually\n")
    sys.exit(2)

open(path, "w").write(new)
print(f"patch-fnptr-agnos: patched {n} fncallN function(s) in {path} "
      "(added CYRIUS_TARGET_AGNOS x86 branches)")
